[GLOBAL]
pants_version = "2.20.1"
backend_packages = [
    "pants.backend.python",
    "pants.backend.python.lint.black",
    "pants.backend.build_files.fmt.black",
]

[anonymous-telemetry]
enabled = false

[python]
interpreter_constraints = [">=3.10"]
enable_resolves = true
resolves = { python-default = "default.lock" }
resolves_to_constraints_file = { python-default = "constraints.txt" }
