[GLOBAL]
pants_version = "2.20.1"
backend_packages = [
    "pants.backend.python",
    "pants.backend.experimental.python.lint.ruff.check",
    "pants.backend.experimental.python.lint.ruff.format",
    "pants.backend.python.typecheck.mypy",
]

[anonymous-telemetry]
enabled = false

[python]
interpreter_constraints = [">=3.10"]
enable_resolves = true
resolves = { python-default = "default.lock" }
resolves_to_constraints_file = { python-default = "constraints.txt" }
