name: Check for updates
on:
  schedule:
    - cron: "0 8 * * *" # Runs every day at 12 midnight PT
  workflow_dispatch:

jobs:
  check-updates:
    if: github.repository_owner == 'ParkingReformNetwork'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - uses: pantsbuild/actions/init-pants@main
        with:
          gha-cache-key: cache0-py${{ matrix.python_version }}
          named-caches-hash: ${{ hashFiles('*.lock') }}
      - name: Update records
        run: pants run src/main.py -- --write
        env:
          SALESFORCE_INSTANCE_URL: ${{ secrets.SALESFORCE_INSTANCE_URL }}
          SALESFORCE_TOKEN: ${{ secrets.SALESFORCE_TOKEN }}
