name: Tests
on: [pull_request, workflow_dispatch]

jobs:
  test:
    if: github.repository_owner == 'ParkingReformNetwork'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - uses: pantsbuild/actions/init-pants@main
        with:
          gha-cache-key: cache0-py${{ matrix.python_version }}
          named-caches-hash: ${{ hashFiles('*.lock') }}
      - name: Lint
        run: pants lint '::'
      - name: Typecheck
        run: pants check '::'
      - name: Run tests
        run: pants test '::'
